server:
  internalPort: 5005
  externalPort: 5005
  runMode: debug
logger:
  filePath: ../logs/
  encoding: json
  level: debug
  logger: zap
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
